version: "3.9"

services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: schooldocs
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    command: gunicorn --bind 0.0.0.0:8000 app.wsgi:application
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=db
      - DB_NAME=schooldocs
      - DB_USER=user
      - DB_PASSWORD=password
      - SENDGRID_API_KEY=your_sendgrid_api_key
      - TWILIO_ACCOUNT_SID=your_twilio_sid
      - TWILIO_AUTH_TOKEN=your_twilio_token
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000

volumes:
  db_data:
